import { Dimensions, StyleSheet } from 'react-native';
import { responsiveFontSize, responsiveHeight, responsiveSpacing, responsiveWidth } from '../utils/responsive';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#31429B',
	},
	container: {
		flex: 1,
		backgroundColor: '#ECECEC',
	},
	brandHeader: {
		backgroundColor: '#31429B',
	},
	brandRow: {
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 16, 14, 24),
		paddingTop: responsiveSpacing(SCREEN_HEIGHT, 16, 14, 22),
		paddingBottom: responsiveSpacing(SCREEN_HEIGHT, 18, 14, 24),
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
	},
	brandLogo: {
		width: responsiveWidth(SCREEN_WIDTH, 0.34, 126, 178),
		height: responsiveHeight(SCREEN_HEIGHT, 0.055, 38, 52),
	},
	nulipaPill: {
		backgroundColor: '#FFFFFF',
		borderRadius: 999,
		paddingVertical: responsiveSpacing(SCREEN_HEIGHT, 7, 6, 10),
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 14, 12, 18),
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
	},
	nulipaIcon: {
		width: responsiveWidth(SCREEN_WIDTH, 0.055, 20, 28),
		height: responsiveWidth(SCREEN_WIDTH, 0.055, 20, 28),
		marginRight: 6,
	},
	nulipaText: {
		color: '#2D3F9E',
		fontWeight: '800',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 14, 12, 16),
		letterSpacing: 0.3,
	},
	brandAccent: {
		height: responsiveHeight(SCREEN_HEIGHT, 0.012, 8, 14),
		backgroundColor: '#F2C919',
	},
	contentWrap: {
		flex: 1,
		paddingHorizontal: responsiveSpacing(SCREEN_WIDTH, 16, 14, 22),
		paddingTop: responsiveSpacing(SCREEN_HEIGHT, 12, 10, 18),
	},
	userRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		alignItems: 'center',
		marginBottom: responsiveSpacing(SCREEN_HEIGHT, 12, 10, 16),
	},
	userInfoRow: {
		flexDirection: 'row',
		alignItems: 'center',
		flex: 1,
		marginRight: 10,
	},
	userTextWrap: {
		flexShrink: 1,
	},
	avatar: {
		width: responsiveWidth(SCREEN_WIDTH, 0.095, 34, 44),
		height: responsiveWidth(SCREEN_WIDTH, 0.095, 34, 44),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.0475, 17, 22),
		marginRight: 10,
	},
	helloText: {
		color: '#6A6A6A',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 14, 12, 16),
		lineHeight: 16,
	},
	nameText: {
		color: '#3E3E3E',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 20, 18, 24),
		fontWeight: '800',
	},
	actionsRow: {
		flexDirection: 'row',
		alignItems: 'center',
	},
	circleAction: {
		width: responsiveWidth(SCREEN_WIDTH, 0.1, 36, 44),
		height: responsiveWidth(SCREEN_WIDTH, 0.1, 36, 44),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.05, 18, 22),
		borderWidth: 2,
		borderColor: '#31429B',
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#F2F3F8',
		marginLeft: 8,
	},
	composeAction: {
		backgroundColor: '#31429B',
	},
	segmentedWrap: {
		flexDirection: 'row',
		backgroundColor: '#DADBE0',
		borderRadius: 16,
		padding: 2,
		marginBottom: responsiveSpacing(SCREEN_HEIGHT, 6, 4, 10),
	},
	segmentItem: {
		flex: 1,
		borderRadius: 14,
		alignItems: 'center',
		justifyContent: 'center',
		paddingVertical: responsiveSpacing(SCREEN_HEIGHT, 6, 5, 8),
	},
	segmentItemActive: {
		backgroundColor: '#31429B',
	},
	segmentText: {
		color: '#8C8D94',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 14, 12, 16),
		fontWeight: '500',
	},
	segmentTextActive: {
		color: '#FFFFFF',
		fontWeight: '700',
	},
	listArea: {
		flex: 1,
	},
	listContent: {
		minHeight: '100%',
		paddingTop: 4,
		paddingBottom: 8,
	},
	loadingWrap: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		paddingTop: 24,
	},
	emptyWrap: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 22,
		paddingTop: 24,
	},
	emptyTitle: {
		color: '#31429B',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 18, 16, 22),
		fontWeight: '800',
		marginBottom: 6,
	},
	emptyText: {
		color: '#6B7280',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 13, 12, 15),
		lineHeight: responsiveFontSize(SCREEN_WIDTH, 18, 16, 22),
		textAlign: 'center',
	},
	contactCard: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#FFFFFF',
		borderRadius: 16,
		padding: responsiveSpacing(SCREEN_WIDTH, 8, 6, 8),
		marginBottom: responsiveSpacing(SCREEN_HEIGHT, 6, 4, 6),
		elevation: 2,
		shadowColor: '#000',
		shadowOpacity: 0.04,
		shadowRadius: 8,
		shadowOffset: { width: 0, height: 4 },
	},
	groupCard: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#FFFFFF',
		borderRadius: 16,
		padding: responsiveSpacing(SCREEN_WIDTH, 8, 6, 8),
		marginBottom: responsiveSpacing(SCREEN_HEIGHT, 6, 4, 6),
		elevation: 2,
		shadowColor: '#000',
		shadowOpacity: 0.04,
		shadowRadius: 8,
		shadowOffset: { width: 0, height: 4 },
	},
	contactAvatar: {
		width: responsiveWidth(SCREEN_WIDTH, 0.115, 42, 52),
		height: responsiveWidth(SCREEN_WIDTH, 0.115, 42, 52),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.0575, 21, 26),
		marginRight: 6,
		borderWidth: 1,
		borderColor: '#E5E7EB',
	},
	contactTextWrap: {
		flex: 1,
	},
	groupTextWrap: {
		flex: 1,
	},
	groupTitleRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 10,
	},
	groupAvatar: {
		width: responsiveWidth(SCREEN_WIDTH, 0.115, 42, 52),
		height: responsiveWidth(SCREEN_WIDTH, 0.115, 42, 52),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.0575, 21, 26),
		marginRight: 6,
		borderWidth: 1,
		borderColor: '#E5E7EB',
	},
	groupName: {
		flex: 1,
		color: '#31429B',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 15, 13, 18),
		fontWeight: '800',
	},
	groupUnreadPill: {
		minWidth: responsiveWidth(SCREEN_WIDTH, 0.06, 22, 28),
		height: responsiveWidth(SCREEN_WIDTH, 0.06, 22, 28),
		borderRadius: responsiveWidth(SCREEN_WIDTH, 0.03, 11, 14),
		paddingHorizontal: 7,
		backgroundColor: '#31429B',
		alignItems: 'center',
		justifyContent: 'center',
	},
	groupUnreadText: {
		color: '#FFFFFF',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 12, 10, 14),
		fontWeight: '800',
	},
	groupMeta: {
		color: '#6B7280',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 12, 10, 14),
		marginTop: 1,
	},
	groupPreview: {
		color: '#3E3E3E',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 13, 12, 15),
		marginTop: 2,
	},
	contactRightWrap: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
	},
	contactUnreadIndicator: {
		width: 10,
		height: 10,
		borderRadius: 5,
		backgroundColor: '#E53935',
	},
	contactName: {
		color: '#31429B',
		fontSize: 15,
		fontWeight: '800',
	},
	contactMeta: {
		color: '#6B7280',
		fontSize: 12,
		marginTop: 1,
	},
	/* Modal / Action sheet */
	modalOverlay: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: 'rgba(0,0,0,0.35)',
	},
	actionSheetWrap: {
		position: 'absolute',
		left: 0,
		right: 0,
		bottom: 0,
		justifyContent: 'flex-end',
		paddingHorizontal: 0,
		paddingBottom: 0,
	},
	actionSheetSafeArea: {
		flex: 1,
		justifyContent: 'flex-end',
		alignItems: 'stretch',
	},
	actionSheet: {
		backgroundColor: '#FFFFFF',
		borderTopLeftRadius: 12,
		borderTopRightRadius: 12,
		paddingVertical: 0,
		maxHeight: SCREEN_HEIGHT * 0.85,
		overflow: 'hidden',
		elevation: 0,
		shadowColor: 'transparent',
		shadowOpacity: 0,
		shadowRadius: 0,
		shadowOffset: { width: 0, height: 0 },
	},
	actionSheetTitle: {
		color: '#31429B',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 16, 14, 18),
		fontWeight: '700',
		fontFamily: 'Poppins',
		paddingHorizontal: 16,
		paddingVertical: 10,
		borderBottomWidth: 1,
		borderBottomColor: '#F3F4F6',
	},
	actionItem: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingVertical: 14,
		paddingHorizontal: 16,
		borderBottomWidth: 1,
		borderBottomColor: '#F3F4F6',
	},
	actionIcon: {
		marginRight: 12,
	},
	actionText: {
		color: '#31429B',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 15, 13, 16),
		fontFamily: 'Poppins',
	},
	favoriteText: {
		color: '#F2C919',
		fontSize: responsiveFontSize(SCREEN_WIDTH, 15, 13, 16),
		fontFamily: 'Poppins',
	},
	destructiveAction: {
		borderTopWidth: 1,
		borderTopColor: '#FEE2E2',
	},
	destructiveText: {
		color: '#DC2626',
		fontWeight: '700',
		fontFamily: 'Poppins',
	},
});

export default styles;