import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#FFFFFF',
	},
	container: {
		flex: 1,
		backgroundColor: '#FFFFFF',
	},
	pageHeaderCard: {
		backgroundColor: '#FFFFFF',
		paddingHorizontal: 22,
		paddingTop: 18,
		paddingBottom: 18,
		borderBottomWidth: 1,
		borderBottomColor: '#E7E9F2',
		shadowColor: '#101828',
		shadowOpacity: 0.08,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 3 },
		elevation: 2,
	},
	pageHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 12,
	},
	pageHeaderTitle: {
		fontSize: 20,
		lineHeight: 26,
		fontFamily: 'Poppins_700Bold',
		color: '#31429B',
		letterSpacing: -0.3,
	},
	scrollContent: {
		paddingTop: 12,
		paddingBottom: 28,
		paddingHorizontal: 12,
	},
	formSurface: {
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#E4E4E4',
		borderRadius: 18,
		padding: 10,
		shadowColor: '#101828',
		shadowOpacity: 0.08,
		shadowRadius: 12,
		shadowOffset: { width: 0, height: 6 },
		elevation: 3,
	},
	eventCard: {
		backgroundColor: '#FFFFFF',
		borderRadius: 16,
		paddingHorizontal: 4,
		paddingTop: 4,
		paddingBottom: 8,
	},
	eventBanner: {
		height: 122,
		borderRadius: 14,
		overflow: 'hidden',
		marginBottom: 10,
	},
	eventBannerImage: {
		borderRadius: 14,
	},
	eventBannerOverlay: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: 'rgba(49, 66, 155, 0.08)',
	},
	eventBannerFallback: {
		height: 122,
		borderRadius: 14,
		backgroundColor: '#31429B',
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: 10,
		paddingHorizontal: 18,
	},
	eventBannerIconWrap: {
		width: 84,
		height: 84,
		borderRadius: 20,
		backgroundColor: 'rgba(255, 255, 255, 0.14)',
		justifyContent: 'center',
		alignItems: 'center',
		marginBottom: 10,
	},
	eventBannerIcon: {
		width: 64,
		height: 64,
	},
	eventBannerFallbackText: {
		fontSize: 10,
		fontFamily: 'Poppins_600SemiBold',
		color: '#FFFFFF',
		letterSpacing: 0.3,
	},
	eventTitle: {
		fontSize: 22,
		lineHeight: 28,
		fontFamily: 'Poppins_700Bold',
		color: '#3C3C3C',
		letterSpacing: -0.4,
	},
	eventDescription: {
		marginTop: 10,
		fontSize: 13,
		lineHeight: 23,
		fontFamily: 'Poppins_400Regular',
		color: '#5E5E5E',
	},
	metaRow: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		gap: 12,
		marginTop: 12,
	},
	metaItem: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 8,
		flexShrink: 1,
		flexBasis: '48%',
		paddingVertical: 4,
	},
	metaText: {
		flexShrink: 1,
		flex: 1,
		fontSize: 12,
		lineHeight: 17,
		fontFamily: 'Poppins_600SemiBold',
		color: '#4F5563',
		minWidth: 0,
	},
	addressRow: {
		marginTop: 8,
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: 6,
	},
	addressText: {
		flex: 1,
		fontSize: 12,
		lineHeight: 18,
		fontFamily: 'Poppins_600SemiBold',
		color: '#4F5563',
		minWidth: 0,
	},
	sectionLabel: {
		marginTop: 12,
		fontSize: 12,
		lineHeight: 17,
		fontFamily: 'Poppins_600SemiBold',
		color: '#5E5E5E',
	},
	privacyCard: {
		marginTop: 10,
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#C7C7C7',
		borderRadius: 12,
		paddingHorizontal: 14,
		paddingVertical: 14,
	},
	privacyTitle: {
		fontSize: 15,
		lineHeight: 20,
		fontFamily: 'Poppins_700Bold',
		color: '#404040',
	},
	privacyText: {
		marginTop: 8,
		fontSize: 13,
		lineHeight: 22,
		fontFamily: 'Poppins_400Regular',
		color: '#4E4E4E',
	},
	choiceGroup: {
		marginTop: 14,
		gap: 14,
	},
	choiceRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 10,
	},
	choiceIcon: {
		width: 18,
		height: 18,
		justifyContent: 'center',
		alignItems: 'center',
	},
	choiceText: {
		fontSize: 13,
		lineHeight: 18,
		fontFamily: 'Poppins_400Regular',
		color: '#4B4B4B',
	},
	inputCard: {
		marginTop: 10,
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#C7C7C7',
		borderRadius: 12,
		paddingHorizontal: 14,
		paddingVertical: 12,
	},
	inputLabel: {
		fontSize: 15,
		lineHeight: 20,
		fontFamily: 'Poppins_700Bold',
		color: '#404040',
	},
	inputDescription: {
		marginTop: 8,
		fontSize: 13,
		lineHeight: 20,
		fontFamily: 'Poppins_400Regular',
		color: '#5A5A5A',
	},
	inputField: {
		marginTop: 12,
		paddingHorizontal: 0,
		paddingTop: 0,
		paddingBottom: 8,
		fontSize: 13,
		fontFamily: 'Poppins_400Regular',
		color: '#404040',
		borderBottomWidth: 1,
		borderBottomColor: '#CFCFCF',
	},
	confirmationCard: {
		marginTop: 10,
		backgroundColor: '#FFFFFF',
		borderWidth: 1,
		borderColor: '#C7C7C7',
		borderRadius: 12,
		paddingHorizontal: 14,
		paddingVertical: 12,
	},
	confirmationText: {
		fontSize: 13,
		lineHeight: 21,
		fontFamily: 'Poppins_400Regular',
		color: '#4E4E4E',
	},
	buttonWrap: {
		marginTop: 16,
		paddingTop: 10,
	},
	primaryButton: {
		backgroundColor: '#F7CE18',
		borderRadius: 999,
		minHeight: 42,
		alignItems: 'center',
		justifyContent: 'center',
	},
	primaryButtonDisabled: {
		opacity: 0.45,
	},
	primaryButtonText: {
		fontSize: 17,
		lineHeight: 22,
		fontFamily: 'Poppins_700Bold',
		color: '#31429B',
		letterSpacing: 0.2,
	},
});

export default styles;
