import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeAreaTop: { flex: 1, backgroundColor: '#31429B' },
  container: { flex: 1, backgroundColor: '#FFFFFF' },
  mainScrollContent: {
    paddingBottom: 0,
    backgroundColor: '#FFFFFF',
  },
  brandHeader: {
    backgroundColor: '#31429B',
  },
  brandRow: {
    backgroundColor: '#31429B',
    paddingHorizontal: 0,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brandAccent: {
    height: 10,
    backgroundColor: '#F2C919',
    width: '100%',
  },
  brandLogo: {
    width: 136,
    height: 42,
  },
  nulipaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
    minWidth: 122,
    justifyContent: 'center',
  },
  nulipaIcon: {
    width: 22,
    height: 22,
    marginRight: 6,
  },
  nulipaText: { color: '#31429B', fontWeight: '800', fontSize: 14, letterSpacing: 0.3 },
  profileSection: { flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: 8, paddingVertical: 14, alignItems: 'center' },
  profileInfo: { flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 56, height: 56, borderRadius: 28, marginRight: 14, borderWidth: 2, borderColor: '#F2C919' },
  greeting: { fontSize: 20, fontWeight: '800', color: '#0A1142' },
  studentId: { fontSize: 12, color: '#666', marginTop: 2 },
  bellIcon: { backgroundColor: '#F2C919', padding: 8, borderRadius: 20 },
  idSection: { paddingHorizontal: 0, marginBottom: 18 },
  profileCardWrapper: {
    marginTop: -8,
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 14,
    elevation: 8,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    marginBottom: 18,
  },
  tabRow: { flexDirection: 'row', marginBottom: -10, zIndex: 1, marginLeft: 15 },
  activeTab: { backgroundColor: '#F2C919', paddingVertical: 8, paddingHorizontal: 20, borderTopLeftRadius: 10, borderTopRightRadius: 10 },
  activeTabText: { color: '#31429B', fontWeight: 'bold' },
  inactiveTab: { backgroundColor: '#E0E0E0', paddingVertical: 8, paddingHorizontal: 20, borderTopLeftRadius: 10, borderTopRightRadius: 10, marginLeft: 10 },
  inactiveTabText: { color: '#666' },
  idCard: {
    borderRadius: 5,
    overflow: 'hidden',
    elevation: 6,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    backgroundColor: '#0A1142',
    height: 220,
  },
  idCardPerspective: {
    position: 'relative',
    height: 220,
    perspective: 1000,
  },
  idCardFace: {
    ...StyleSheet.absoluteFillObject,
    backfaceVisibility: 'hidden',
    borderRadius: 8,
    overflow: 'hidden',
  },
  idCardFrontFace: {
    zIndex: 2,
  },
  idCardBackFace: {
    zIndex: 1,
  },
  idBackground: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  idBackgroundImage: {
    borderRadius: 8,
  },
  idPhoto: {
    position: 'absolute',
    top: '13%',
    right: '1.3%',
    width: '30%',
    height: '28%',
  },
  idCardContent: {
    position: 'absolute',
    top: '26%',
    left: '6%',
    bottom: '10%',
    width: '62%',
  },
  idName: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 18,
    top: '7%',
  },
  idCourse: {
    color: '#FFFFFF',
    fontSize: 12,
    marginTop: 6,
    top: '4%',
  },
  idClass: {
    color: '#FFFFFF',
    fontSize: 12,
    marginTop: 2,
    top: '4%',
  },
  idBackImage: {
    width: '100%',
    height: '100%',
  },
  sectionContainer: { marginBottom: 0 },
  sectionInset: { marginLeft: 0, marginRight: 0 },
  sectionNudgeRight: { transform: [{ translateX: 10 }] },
  quickLinksSection: { marginTop: 8, marginBottom: 12, paddingBottom: 8 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: '#31429B', marginBottom: 8 },
  horizontalScroll: { flexDirection: 'row' },
  horizontalScrollContent: {
    paddingBottom: 8,
  },
  promoCard: { width: 280, height: 130, backgroundColor: '#FDEAA6', borderRadius: 12, marginRight: 12, padding: 12, overflow: 'hidden', flexDirection: 'row' },
  promoLeft: {
    flex: 1,
    borderRadius: 10,
    backgroundColor: '#F5D671',
    marginRight: 10,
  },
  promoRight: {
    flex: 1.1,
    justifyContent: 'center',
  },
  promoEyebrow: {
    color: '#31429B',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 2,
  },
  promoTitleMain: {
    color: '#31429B',
    fontSize: 20,
    lineHeight: 22,
    fontWeight: '900',
  },
  promoTitleSub: {
    color: '#31429B',
    fontSize: 18,
    lineHeight: 20,
    fontWeight: '900',
  },
  promoDate: {
    marginTop: 8,
    color: '#31429B',
    fontSize: 11,
    fontWeight: '700',
  },
  promoLocation: {
    color: '#31429B',
    fontSize: 11,
    lineHeight: 14,
  },
  quickLinksRow: { flexDirection: 'row', justifyContent: 'space-between' },
  quickLinksScrollContent: {
    paddingBottom: 8,
  },
  quickLinkBox: {
    width: 192,
    minHeight: 64,
    backgroundColor: '#FFFFFF',
    paddingVertical: 16,
    paddingHorizontal: 14,
    borderRadius: 14,
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 12,
    elevation: 3,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
  },
  quickLinkText: {
    marginLeft: 12,
    color: '#31429B',
    fontWeight: '800',
    fontSize: 14,
    lineHeight: 18,
  },
  quickLinkIcon: {
    width: 36,
    height: 36,
  },
  quickLinkIconNU: {
    width: 26,
    height: 26,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
  },
  modalContainer: {
    backgroundColor: '#FFF',
    height: '85%',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    overflow: 'hidden',
    marginTop: 50,
  },
  modalSideContainer: {
    backgroundColor: '#FFF',
    position: 'absolute',
    right: 0,
    top: 0,
    bottom: 0,
    width: '100%',
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
    overflow: 'hidden',
  },
  modalHeader: {
    backgroundColor: '#31429B',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 15,
    paddingHorizontal: 20,
  },
  modalTitle: {
    color: '#FFF',
    fontSize: 20,
    fontWeight: 'bold',
  },
  modalHeaderSpacer: {
    width: 28,
  },
  closeBtn: { padding: 5 },
  modalAccentLine: {
    height: 5,
    backgroundColor: '#F2C919',
  },
  notifList: {
    padding: 20,
    flexGrow: 1,
  },
  emptyNotifWrap: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 30,
  },
  emptyNotifText: {
    color: '#666',
    fontSize: 14,
  },
  notifCard: {
    flexDirection: 'row',
    marginBottom: 25,
    alignItems: 'flex-start',
  },
  notifAvatar: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#F2C919',
    marginRight: 15,
  },
  notifBody: {
    flex: 1,
  },
  notifName: {
    color: '#31429B',
    fontWeight: 'bold',
    fontSize: 14,
    lineHeight: 20,
  },
  notifAction: {
    color: '#666',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 2,
  },
  notifTime: {
    color: '#A0A0A0',
    fontSize: 12,
    marginBottom: 8,
  },
  notifButtonsRow: {
    flexDirection: 'row',
  },
  btnAccepted: {
    backgroundColor: '#31429B',
    paddingVertical: 4,
    paddingHorizontal: 15,
    borderRadius: 15,
    marginRight: 10,
  },
  btnAcceptedText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  btnDelete: {
    backgroundColor: '#D3D3D3',
    paddingVertical: 4,
    paddingHorizontal: 15,
    borderRadius: 15,
  },
  btnDeleteText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  sideMenuRoot: {
    flex: 1,
    flexDirection: 'row',
  },
  sideMenuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
  },
  sideMenuContainer: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: '90%',
    maxWidth: 340,
    backgroundColor: '#E9E9E9',
    borderTopRightRadius: 26,
    borderBottomRightRadius: 26,
    overflow: 'hidden',
  },
  sideMenuHeader: {
    backgroundColor: '#31429B',
    paddingHorizontal: 20,
    paddingTop: 52,
    paddingBottom: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sideMenuTitle: {
    color: '#FFF',
    fontSize: 28,
    fontWeight: '700',
  },
  sideMenuAccent: {
    height: 6,
    backgroundColor: '#F2C919',
  },
  sideMenuBody: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 16,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  sideMenuFooter: {
    paddingHorizontal: 20,
    paddingBottom: 26,
    paddingTop: 8,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  signOutButton: {
    width: '74%',
    backgroundColor: '#FF1515',
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  menuIconCircle: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#F2C919',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuTextWrap: {
    marginLeft: 10,
    flex: 1,
  },
  menuItemTitle: {
    color: '#31429B',
    fontWeight: '700',
    fontSize: 18,
  },
  menuItemSub: {
    color: '#4A5FAE',
    fontSize: 11,
    fontStyle: 'italic',
    marginTop: 1,
  },
  signOutButtonText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: '700',
  },
});

export default styles;
