import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#31429B',
	},
	container: {
		flex: 1,
		backgroundColor: '#F5F6FA',
	},
	content: {
		paddingBottom: 24,
	},
	searchRow: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 16,
		paddingVertical: 18,
		backgroundColor: '#FFFFFF',
		borderBottomWidth: 1,
		borderBottomColor: '#D9D9D9',
	},
	searchAvatar: {
		width: 34,
		height: 34,
		borderRadius: 17,
		marginRight: 10,
		backgroundColor: '#E5E7EB',
	},
	searchWrap: {
		flex: 1,
		height: 40,
		borderRadius: 999,
		backgroundColor: '#F1F1F1',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingLeft: 18,
		paddingRight: 14,
	},
	searchInput: {
		flex: 1,
		fontSize: 15,
		color: '#5A5A5A',
		paddingVertical: 0,
		paddingRight: 10,
	},
	createPostCard: {
		marginHorizontal: 6,
		marginTop: 10,
		backgroundColor: '#FFFFFF',
		borderRadius: 18,
		borderWidth: 1,
		borderColor: '#DCDDE4',
		paddingHorizontal: 18,
		paddingTop: 16,
		paddingBottom: 18,
	},
	createPostTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: '800',
		color: '#31429B',
		marginBottom: 12,
	},
	composeRow: {
		flexDirection: 'row',
		alignItems: 'center',
		marginBottom: 10,
	},
	composeBubble: {
		flex: 1,
		minHeight: 46,
		borderRadius: 999,
		backgroundColor: '#F4C91B',
		flexDirection: 'row',
		alignItems: 'center',
		paddingLeft: 10,
		paddingRight: 14,
	},
	composeAvatar: {
		width: 28,
		height: 28,
		borderRadius: 14,
		marginRight: 10,
		backgroundColor: '#E5E7EB',
	},
	composePrompt: {
		flex: 1,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: '700',
		color: '#31429B',
	},
	sendButton: {
		marginLeft: 12,
		width: 34,
		height: 34,
		borderRadius: 17,
		alignItems: 'center',
		justifyContent: 'center',
	},
	actionRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 10,
		flexWrap: 'wrap',
	},
	actionChip: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#F0EDF6',
		borderRadius: 999,
		paddingHorizontal: 12,
		paddingVertical: 6,
	},
	actionChipText: {
		marginLeft: 6,
		fontSize: 11,
		lineHeight: 14,
		fontWeight: '700',
		color: '#4C4F87',
	},
	emptySpace: {
		flex: 1,
		minHeight: 220,
	},
});

export default styles;