import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#31429B',
	},
	container: {
		flex: 1,
		backgroundColor: '#F5F6FA',
	},
	content: {
		paddingBottom: 24,
	},
	searchRow: {
		flexDirection: 'row',
		alignItems: 'center',
		paddingHorizontal: 16,
		paddingVertical: 18,
		backgroundColor: '#FFFFFF',
		borderBottomWidth: 1,
		borderBottomColor: '#D9D9D9',
	},
	searchAvatar: {
		width: 34,
		height: 34,
		borderRadius: 17,
		marginRight: 10,
		backgroundColor: '#E5E7EB',
	},
	searchWrap: {
		flex: 1,
		height: 40,
		borderRadius: 999,
		backgroundColor: '#F1F1F1',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingLeft: 18,
		paddingRight: 14,
	},
	searchInput: {
		flex: 1,
		fontSize: 15,
		color: '#5A5A5A',
		paddingVertical: 0,
		paddingRight: 10,
	},
	createPostCard: {
		marginHorizontal: 6,
		marginTop: 10,
		backgroundColor: '#FFFFFF',
		borderRadius: 18,
		borderWidth: 1,
		borderColor: '#DCDDE4',
		paddingHorizontal: 18,
		paddingTop: 16,
		paddingBottom: 18,
	},
	createPostTitle: {
		fontSize: 18,
		lineHeight: 22,
		fontWeight: '800',
		color: '#31429B',
		marginBottom: 12,
	},
	composeRow: {
		flexDirection: 'row',
		alignItems: 'center',
		marginBottom: 10,
	},
	composeBubble: {
		flex: 1,
		minHeight: 46,
		borderRadius: 999,
		backgroundColor: '#F4C91B',
		flexDirection: 'row',
		alignItems: 'center',
		paddingLeft: 10,
		paddingRight: 14,
	},
	composeAvatar: {
		width: 28,
		height: 28,
		borderRadius: 14,
		marginRight: 10,
		backgroundColor: '#E5E7EB',
	},
	composePrompt: {
		flex: 1,
		fontSize: 13,
		lineHeight: 18,
		fontWeight: '700',
		color: '#31429B',
	},
	sendButton: {
		marginLeft: 12,
		width: 34,
		height: 34,
		borderRadius: 17,
		alignItems: 'center',
		justifyContent: 'center',
	},
	actionRow: {
		flexDirection: 'row',
		alignItems: 'center',
		gap: 10,
		flexWrap: 'wrap',
	},
	actionChip: {
		flexDirection: 'row',
		alignItems: 'center',
		backgroundColor: '#F0EDF6',
		borderRadius: 999,
		paddingHorizontal: 12,
		paddingVertical: 6,
	},
	actionChipText: {
		marginLeft: 6,
		fontSize: 11,
		lineHeight: 14,
		fontWeight: '700',
		color: '#4C4F87',
	},
	feedSection: {
		paddingHorizontal: 6,
		paddingTop: 16,
	},
	feedHeaderRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginBottom: 10,
		paddingHorizontal: 6,
	},
	feedTitle: {
		fontSize: 16,
		fontWeight: '800',
		color: '#24346F',
	},
	feedCount: {
		fontSize: 12,
		fontWeight: '700',
		color: '#8A94A6',
	},
	feedStateCard: {
		backgroundColor: '#FFFFFF',
		borderRadius: 18,
		paddingVertical: 18,
		paddingHorizontal: 16,
		alignItems: 'center',
		justifyContent: 'center',
		gap: 10,
		marginBottom: 12,
	},
	feedStateText: {
		fontSize: 13,
		color: '#5A5A5A',
		fontWeight: '600',
		textAlign: 'center',
	},
	postCard: {
		backgroundColor: '#FFFFFF',
		borderRadius: 18,
		borderWidth: 1,
		borderColor: '#DCDDE4',
		padding: 14,
		marginBottom: 12,
		marginHorizontal: 6,
	},
	postHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		marginBottom: 12,
	},
	postAvatar: {
		width: 42,
		height: 42,
		borderRadius: 21,
		backgroundColor: '#E5E7EB',
		marginRight: 10,
	},
	postHeaderTextWrap: {
		flex: 1,
	},
	postAuthorName: {
		fontSize: 14,
		fontWeight: '800',
		color: '#24346F',
	},
	postMeta: {
		fontSize: 11,
		color: '#7A7A7A',
		marginTop: 2,
	},
	postStatusPill: {
		paddingHorizontal: 10,
		paddingVertical: 5,
		borderRadius: 999,
		backgroundColor: '#EEF2FF',
	},
	postStatusText: {
		fontSize: 11,
		fontWeight: '700',
		color: '#31429B',
	},
	postCaption: {
		fontSize: 14,
		lineHeight: 20,
		color: '#2E2E2E',
		marginBottom: 12,
	},
	postReactionRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		marginTop: 12,
		paddingTop: 12,
		borderTopWidth: 1,
		borderTopColor: '#E9ECF3',
	},
	postCommentButton: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 6,
		minWidth: 92,
		paddingHorizontal: 14,
		paddingVertical: 8,
		borderRadius: 999,
		backgroundColor: '#F3F4F6',
	},
	postActionButtonText: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: '800',
		color: '#56607A',
	},
	postActionCountText: {
		marginLeft: 2,
		fontSize: 12,
		fontWeight: '700',
		color: '#5B647A',
	},
	postReactionButton: {
		minWidth: 88,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 6,
		paddingHorizontal: 14,
		paddingVertical: 8,
		borderRadius: 999,
		backgroundColor: '#EEF2FF',
	},
	postReactionButtonActive: {
		backgroundColor: '#FDE8E7',
	},
	postReactionButtonText: {
		fontSize: 12,
		lineHeight: 16,
		fontWeight: '800',
		color: '#31429B',
	},
	postReactionButtonTextActive: {
		color: '#D92D20',
	},
	postTwoGrid: {
		flexDirection: 'row',
		gap: 8,
		alignItems: 'flex-start',
	},
	postTwoPrimaryTile: {
		flex: 1.15,
		borderRadius: 4,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		alignSelf: 'flex-start',
	},
	postTwoSecondaryTile: {
		flex: 0.85,
		borderRadius: 4,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		alignSelf: 'flex-start',
	},
	postThreeCollage: {
		flexDirection: 'row',
		gap: 8,
		alignItems: 'flex-start',
	},
	postThreeLeftTile: {
		flex: 1.45,
		borderRadius: 4,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		alignSelf: 'flex-start',
	},
	postThreeRightColumn: {
		flex: 0.9,
		gap: 8,
		alignSelf: 'flex-start',
	},
	postThreeRightTile: {
		borderRadius: 4,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		width: '100%',
		alignSelf: 'flex-start',
	},
	postFourCollage: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		gap: 8,
		alignItems: 'flex-start',
	},
	postFourLeadTile: {
		flex: 1.45,
		borderRadius: 4,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		alignSelf: 'flex-start',
	},
	postFourSideColumn: {
		flex: 0.9,
		gap: 8,
		alignSelf: 'flex-start',
	},
	postFourSideTile: {
		width: '100%',
		borderRadius: 4,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		alignSelf: 'flex-start',
	},
	postFivePlusGrid: {
		flexDirection: 'row',
		flexWrap: 'wrap',
		justifyContent: 'space-between',
		gap: 8,
	},
	postFivePlusTile: {
		width: '48.5%',
		aspectRatio: 1,
		borderRadius: 4,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
	},
	postImageOverlay: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		backgroundColor: 'rgba(20, 25, 42, 0.45)',
		alignItems: 'center',
		justifyContent: 'center',
	},
	postImageOverlayText: {
		fontSize: 28,
		lineHeight: 32,
		fontWeight: '900',
		color: '#FFFFFF',
		textShadowColor: 'rgba(0, 0, 0, 0.35)',
		textShadowOffset: { width: 0, height: 1 },
		textShadowRadius: 4,
	},
	postSingleImageWrap: {
		borderRadius: 4,
		overflow: 'hidden',
		backgroundColor: '#F3F4F6',
		width: '100%',
		alignSelf: 'stretch',
	},
	postCollageImage: {
		width: '100%',
		height: '100%',
		backgroundColor: '#F3F4F6',
	},
	postImagePressable: {
		width: '100%',
		height: '100%',
	},
	viewerBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(0, 0, 0, 0.92)',
		alignItems: 'center',
		justifyContent: 'center',
	},
	viewerContent: {
		width: '100%',
		height: '100%',
		alignItems: 'center',
		justifyContent: 'center',
	},
	viewerImagePressable: {
		alignItems: 'center',
		justifyContent: 'center',
	},
	viewerImage: {
		backgroundColor: 'transparent',
	},
	viewerCloseButton: {
		position: 'absolute',
		top: 52,
		right: 18,
		width: 40,
		height: 40,
		borderRadius: 20,
		backgroundColor: 'rgba(255, 255, 255, 0.18)',
		alignItems: 'center',
		justifyContent: 'center',
	},
	commentsModalBackdrop: {
		flex: 1,
		backgroundColor: 'rgba(15, 23, 42, 0.58)',
		justifyContent: 'flex-end',
	},
	commentsSheet: {
		backgroundColor: '#FFFFFF',
		borderTopLeftRadius: 24,
		borderTopRightRadius: 24,
		paddingHorizontal: 18,
		paddingTop: 16,
		paddingBottom: 20,
		height: '85%',
	},
	commentsHeaderRow: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		justifyContent: 'space-between',
		marginBottom: 18,
	},
	commentsTitle: {
		fontSize: 20,
		lineHeight: 24,
		fontWeight: '900',
		color: '#24346F',
	},
	commentsSubtitle: {
		marginTop: 4,
		fontSize: 12,
		fontWeight: '700',
		color: '#7A7A7A',
	},
	commentsCloseButton: {
		width: 36,
		height: 36,
		borderRadius: 18,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#EEF2FF',
	},
	commentsEmptyState: {
		flexGrow: 1,
		minHeight: 150,
		borderRadius: 20,
		borderWidth: 1,
		borderColor: '#E5E7EB',
		backgroundColor: '#FAFBFD',
		alignItems: 'center',
		justifyContent: 'center',
		gap: 10,
		paddingHorizontal: 18,
		marginBottom: 16,
	},
	commentsEmptyText: {
		fontSize: 13,
		fontWeight: '700',
		color: '#6B7280',
		textAlign: 'center',
	},
	commentsList: {
		flexGrow: 1,
		marginBottom: 16,
	},
	commentItem: {
		flexDirection: 'row',
		alignItems: 'flex-start',
		gap: 10,
		marginBottom: 12,
	},
	commentAvatar: {
		width: 34,
		height: 34,
		borderRadius: 17,
		backgroundColor: '#E5E7EB',
	},
	commentBubble: {
		flex: 1,
		borderRadius: 16,
		backgroundColor: '#F8FAFC',
		borderWidth: 1,
		borderColor: '#E2E8F0',
		paddingHorizontal: 12,
		paddingVertical: 10,
	},
	commentBubbleHeader: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		gap: 8,
		marginBottom: 6,
	},
	commentAuthorName: {
		flex: 1,
		fontSize: 13,
		fontWeight: '800',
		color: '#24346F',
	},
	commentTimestamp: {
		fontSize: 10,
		fontWeight: '700',
		color: '#94A3B8',
	},
	commentText: {
		fontSize: 13,
		lineHeight: 18,
		color: '#334155',
	},
	commentComposer: {
		flexDirection: 'row',
		alignItems: 'flex-end',
		gap: 0,
	},
	commentInputWrap: {
		flex: 1,
		position: 'relative',
	},
	commentInput: {
		minHeight: 48,
		maxHeight: 110,
		borderRadius: 16,
		borderWidth: 1,
		borderColor: '#D9DDE8',
		backgroundColor: '#F8FAFC',
		paddingHorizontal: 14,
		paddingRight: 88,
		paddingVertical: 12,
		fontSize: 14,
		lineHeight: 20,
		color: '#24346F',
	},
	commentSendButtonInside: {
		position: 'absolute',
		right: 8,
		bottom: 8,
		minWidth: 74,
		height: 32,
		borderRadius: 16,
		paddingHorizontal: 14,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: '#31429B',
	},
	commentSendButtonDisabled: {
		opacity: 0.45,
	},
	commentSendButtonText: {
		fontSize: 13,
		lineHeight: 18,
		fontWeight: '800',
		color: '#FFFFFF',
	},
	postSingleImage: {
		width: '100%',
		height: '100%',
		backgroundColor: '#F3F4F6',
	},
	postMediaImage: {
		width: '100%',
		height: '100%',
		backgroundColor: '#F3F4F6',
	},
	emptySpace: {
		flex: 1,
		minHeight: 220,
	},
});

export default styles;