import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#31429B',
  },
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  brandHeader: {
    backgroundColor: '#31429B',
  },
  brandRow: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  brandLogo: {
    width: 136,
    height: 42,
  },
  nulipaPill: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 7,
    minWidth: 122,
    justifyContent: 'center',
  },
  nulipaIcon: {
    width: 22,
    height: 22,
    marginRight: 6,
  },
  nulipaText: {
    color: '#31429B',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  brandAccent: {
    height: 10,
    backgroundColor: '#F3CB21',
  },
  content: {
    flexGrow: 1,
    paddingBottom: 18,
    backgroundColor: '#FFFFFF',
  },
  stateWrap: {
    minHeight: 420,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
    paddingHorizontal: 20,
  },
  errorText: {
    color: '#B91C1C',
    textAlign: 'center',
    fontSize: 15,
  },
  actionButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: '#31429B',
    borderRadius: 14,
  },
  actionButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '700',
  },
  heroCard: {
    marginTop: 0,
    marginHorizontal: 0,
    backgroundColor: '#FFFFFF',
    borderBottomLeftRadius: 38,
    borderBottomRightRadius: 38,
    padding: 16,
    marginBottom: -24,
    position: 'relative',
    zIndex: 2,
    shadowColor: '#111827',
    shadowOpacity: 0.10,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  heroRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatar: {
    backgroundColor: '#E5E7EB',
    marginRight: 14,
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
  },
  heroTitleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  name: {
    flex: 1,
    paddingRight: 8,
    color: '#384A9C',
    fontSize: 22,
    lineHeight: 24,
    fontWeight: '900',
  },
  iconButton: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#384A9C',
  },
  tagPill: {
    marginTop: 8,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: '#FFD84D',
  },
  tagText: {
    marginLeft: 4,
    color: '#31429B',
    fontSize: 11,
    fontWeight: '800',
  },
  statsRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'flex-end',
  },
  statBlock: {
    marginRight: 24,
  },
  statValue: {
    fontSize: 24,
    lineHeight: 26,
    color: '#30343C',
    fontWeight: '500',
  },
  statLabel: {
    marginTop: 2,
    color: '#5C6471',
    fontSize: 12,
  },
  sectionBlock: {
    marginTop: 18,
    paddingHorizontal: 0,
  },
  postsSectionBlock: {
    marginTop: 18,
    paddingHorizontal: 10,
  },
  aboutSectionWrap: {
    marginTop: 1,
    paddingHorizontal: 0,
    position: 'relative',
    zIndex: 1,
  },
  aboutSectionCard: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingTop: 32,
    paddingBottom: 12,
    minHeight: 150,
    shadowColor: '#111827',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  bioSectionCard: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingTop: 22,
    paddingBottom: 12,
    minHeight: 150,
    borderRadius: 22,
    shadowColor: '#111827',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  workSectionCard: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingTop: 22,
    paddingBottom: 12,
    borderRadius: 22,
    shadowColor: '#111827',
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  sectionHeading: {
    color: '#404040',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  editPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
    borderColor: '#B8BCC6',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#FFFFFF',
  },
  editPillText: {
    color: '#404040',
    fontSize: 11,
    fontWeight: '700',
  },
  aboutItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 6,
    marginBottom: 6,
  },
  aboutText: {
    marginLeft: 8,
    color: '#404040',
    fontSize: 14,
  },
  biographyText: {
    color: '#404040',
    fontSize: 14,
    lineHeight: 20,
    paddingHorizontal: 6,
  },
  workCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    paddingVertical: 12,
    paddingHorizontal: 10,
    shadowColor: '#111827',
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  workRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  workNavButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    shadowColor: '#111827',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  workContent: {
    flex: 1,
    paddingHorizontal: 10,
  },
  workTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  workTitle: {
    marginLeft: 6,
    color: '#30343C',
    fontSize: 15,
    fontWeight: '800',
  },
  workSubtitle: {
    marginTop: 2,
    color: '#31429B',
    fontSize: 12,
    fontWeight: '600',
  },
  workPeriod: {
    marginTop: 10,
    color: '#5C6471',
    fontSize: 12,
  },
  workLocationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 4,
  },
  workLocation: {
    marginLeft: 6,
    color: '#5C6471',
    fontSize: 12,
  },
  workDescription: {
    marginTop: 10,
    color: '#404040',
    fontSize: 12,
    lineHeight: 18,
  },
  paginationRow: {
    marginTop: 10,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
  },
  paginationDot: {
    width: 7,
    height: 7,
    borderRadius: 3.5,
    marginHorizontal: 3,
    backgroundColor: '#D9DCE3',
  },
  paginationDotActive: {
    width: 18,
    backgroundColor: '#31429B',
  },
  postsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 16,
    minHeight: 84,
  },
  emptyPostsText: {
    color: '#8A8F9A',
    fontSize: 13,
  },
});

export default styles;