import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#31429B',
	},
	container: {
		flex: 1,
		backgroundColor: '#FFFFFF',
	},
	titleStrip: {
		backgroundColor: '#FFFFFF',
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingHorizontal: 18,
		paddingVertical: 12,
	},
	title: {
		fontSize: 20,
		fontWeight: '800',
		color: '#31429B',
		lineHeight: 23,
	},
	homeButton: {
		width: 44,
		height: 44,
		borderRadius: 22,
		backgroundColor: '#F2C919',
		alignItems: 'center',
		justifyContent: 'center',
	},
	body: {
		flex: 1,
	},
	cardSection: {
		backgroundColor: '#31429B',
		alignItems: 'center',
		justifyContent: 'center',
		flex: 1,
		paddingVertical: 8,
	},
	coverFrame: {
		borderRadius: 18,
		overflow: 'hidden',
		backgroundColor: '#2D3E97',
		shadowColor: '#000000',
		shadowOpacity: 0.22,
		shadowRadius: 10,
		shadowOffset: { width: 0, height: 7 },
		elevation: 7,
	},
	coverImage: {
		flex: 1,
		justifyContent: 'space-between',
	},
	coverImageInner: {
		borderRadius: 18,
	},
	coverShade: {
		...StyleSheet.absoluteFillObject,
		backgroundColor: 'rgba(37, 48, 124, 0.42)',
	},
	coverAccentLeft: {
		position: 'absolute',
		left: -14,
		top: 48,
		width: '52%',
		height: '54%',
		backgroundColor: 'rgba(248, 205, 18, 0.72)',
		transform: [{ rotate: '35deg' }],
	},
	coverAccentBottom: {
		position: 'absolute',
		left: 0,
		right: 0,
		bottom: 0,
		height: 18,
		backgroundColor: '#F2C919',
	},
	coverHeaderText: {
		position: 'absolute',
		top: 14,
		right: 14,
		alignItems: 'flex-end',
	},
	coverBrand: {
		fontSize: 26,
		lineHeight: 30,
		fontWeight: '900',
		color: '#FFFFFF',
	},
	coverLevels: {
		marginTop: 5,
		fontSize: 13,
		lineHeight: 16,
		color: '#FFFFFF',
		textAlign: 'right',
	},
	coverFooterText: {
		position: 'absolute',
		left: 14,
		bottom: 12,
	},
	coverTagline: {
		fontSize: 11,
		lineHeight: 14,
		fontStyle: 'italic',
		color: '#FFFFFF',
		fontWeight: '600',
	},
	pageControls: {
		backgroundColor: '#FFFFFF',
		alignItems: 'center',
		paddingTop: 8,
		paddingBottom: 8,
		borderBottomWidth: 1,
		borderBottomColor: '#E5E7EB',
	},
	navRow: {
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'center',
	},
	navButton: {
		width: 38,
		height: 38,
		alignItems: 'center',
		justifyContent: 'center',
	},
	pageCounter: {
		marginTop: 4,
		fontSize: 13,
		lineHeight: 16,
		color: '#31429B',
		fontWeight: '600',
	},
	navbar: {
		height: 65,
		backgroundColor: '#FFFFFF',
		borderTopWidth: 1,
		borderTopColor: '#E2E8F0',
		position: 'absolute',
		left: 0,
		right: 0,
		bottom: 0,
		flexDirection: 'row',
		alignItems: 'center',
		justifyContent: 'space-between',
		paddingTop: 0,
		paddingBottom: 0,
		paddingHorizontal: 0,
		elevation: 10,
	},
	navbarButton: {
		bottom: 10,
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		height: '100%',
		paddingVertical: 0,
	},
});

export default styles;
